increment #9, save urls to file
sashaaro/url-shortener pull request #11
Opened 2024-04-05 17:02 UTC by sashaaro

2024-04-09 14:52 UTC, arttet requested changes

2024-04-09 19:15 UTC, sashaaro commented on internal/adapters/logger.go
> +var Logger zap.SugaredLogger
исправил

2024-04-09 19:16 UTC, sashaaro commented on internal/handlers/handlers.go
> +	body, err := GetDecompressedBody(request)
исправил

2024-04-09 19:17 UTC, sashaaro commented on internal/handlers/handlers.go
> +	err = json.NewEncoder(w).Encode(ShortenResponse{Result: createPublicURL(key)})
не понял. почему? middleware отвечает за gzip. тут же я просто json записывают в ответ.

2024-04-10 09:27 UTC, arttet approved these changes

2024-04-10 17:27 UTC, merged