iter13: handle unique constraint error with conflict code
sashaaro/url-shortener pull request #16
Opened 2024-04-16 18:37 UTC by sashaaro

2024-04-17 05:53 UTC, arttet requested changes

2024-04-17 05:53 UTC, arttet commented on internal/adapters/postgres.go
> +func (r *PgURLRepository) BatchAdd(batch []domain.BatchItem) error {
CHANGE REQUEST: you have to provide `context` as a parameter of function.

2024-04-17 05:53 UTC, arttet commented on internal/adapters/postgres.go
> +			ok := errors.As(err, &pgErr)
CLARIFICATION: Why not `errors.Is` ?

2024-04-17 05:53 UTC, arttet commented on internal/adapters/postgres.go
> +		panic(err)
CHANGE REQUEST: please don't panic here

2024-04-17 05:53 UTC, arttet commented on internal/adapters/postgres.go
> +	_, err := conn.Exec(context.Background(), "CREATE TABLE IF NOT EXISTS urls (key text PRIMARY KEY, url text UNIQUE)")
CHANGE REQUEST: please use migrations

2024-04-17 18:34 UTC, sashaaro commented on internal/adapters/postgres.go
> +			ok := errors.As(err, &pgErr)
Because I need to receive an instance of PgError. and check code. I do it above `pgErr.Code == pgerrcode.UniqueViolation`
as I know `error.Is` just check is error same type or not

2024-04-20 07:12 UTC, sashaaro commented on internal/adapters/postgres.go
> +func (r *PgURLRepository) BatchAdd(batch []domain.BatchItem) error {
added context as argument in repository's methods

2024-04-21 10:31 UTC, sashaaro commented on internal/adapters/postgres.go
> +		panic(err)
fixed

2024-04-21 11:01 UTC, sashaaro commented on internal/adapters/postgres.go
> +	_, err := conn.Exec(context.Background(), "CREATE TABLE IF NOT EXISTS urls (key text PRIMARY KEY, url text UNIQUE)")
added goose migraitons

2024-04-21 14:46 UTC, arttet approved these changes

2024-04-21 14:46 UTC, arttet commented on migrations/20240420072526_add_table_urls.go
> +	_, err := tx.ExecContext(ctx, "CREATE TABLE urls (key text PRIMARY KEY, url text UNIQUE)")
SUGGESTION: if I were you, I would use the `SQL` file.

2024-04-21 14:46 UTC, arttet commented on migrations/20240420072526_add_table_urls.go
> +	_, err := tx.ExecContext(ctx, "CREATE TABLE urls (key text PRIMARY KEY, url text UNIQUE)")
```suggestion
	_, err := tx.ExecContext(ctx, "CREATE TABLE url (id VARCHAR(8) PRIMARY KEY, url VARCHAR(2048) UNIQUE)")
```

2024-04-22 05:42 UTC, merged