Iter19
sashaaro/url-shortener pull request #21
Opened 2024-09-02 20:07 UTC by sashaaro

2024-09-03 11:20 UTC, s-shpak requested changes
Сейчас по моим подсчетам покрытие тестами составляет `43.1%` (`go test -v -coverpkg=./... -coverprofile=profile.cov ./... && go tool cover -func profile.cov`)

Увеличь его, пожалуйста, до 55% (как в задании) и добавь в `README.md` инструкции по расчету тестового покрытия.

2024-09-07 05:27 UTC, sashaaro commented on .github/workflows/shortenertest.yml
видимо да, поправил, теперь диф только на одной строчке с изменением версии golang

2024-09-07 05:27 UTC, sashaaro commented on .github/workflows/statictest.yml
поправил

2024-09-07 05:37 UTC, sashaaro commented on internal/statcheck/passes/exitonmain/exitonmain.go
> +				inMain--
точно, переделал на первый вариант

2024-09-07 05:40 UTC, sashaaro commented on internal/statcheck/passes/exitonmain/exitonmain.go
> +			switch x := node.(type) {
да, удалил свитчь, поменял на просто `callExpr, ok := bodyNode.(*ast.CallExpr); ok`

2024-09-07 06:25 UTC, sashaaro commented
> Сейчас по моим подсчетам покрытие тестами составляет `43.1%` (`go test -v -coverpkg=./... -coverprofile=profile.cov ./... && go tool cover -func profile.cov`)
> 
> Увеличь его, пожалуйста, до 55% (как в задании) и добавь в `README.md` инструкции по расчету тестового покрытия.

поднял до 56.8%

2024-09-07 10:04 UTC, s-shpak requested changes

2024-09-07 10:04 UTC, s-shpak commented on internal/statcheck/passes/exitonmain/exitonmain.go
> +	for _, file := range pass.Files {
Уменьши здесь вложенность, пожалуйста. Один из способов -- проверяй обратное условие раньше и выходи из функции, если оно выполняется

2024-09-07 10:04 UTC, s-shpak commented on internal/statcheck/passes/exitonmain/exitonmain.go
> +			return true
Здесь точно должен быть `true` ? В этом случае необходимо продолжать обход AST ?

2024-09-09 18:15 UTC, sashaaro commented on internal/statcheck/passes/exitonmain/exitonmain.go
> +			return true
поправил

2024-09-09 18:16 UTC, sashaaro commented on internal/statcheck/passes/exitonmain/exitonmain.go
> +	for _, file := range pass.Files {
поправил

2024-09-10 08:12 UTC, s-shpak approved these changes

2024-09-10 12:01 UTC, merged