iter24: stats
sashaaro/url-shortener pull request #23
Opened 2024-09-23 19:47 UTC by sashaaro

2024-10-08 09:39 UTC, s-shpak requested changes

2024-10-08 09:39 UTC, s-shpak commented on internal/grpc/grpc_servcie.go
> +	key := s.genShortURLToken()
Кажется, что эта логика повторяет логику для REST-API, можно ли уменьшить дублирование логики ?

2024-10-08 09:39 UTC, s-shpak commented on internal/handlers/middleware.go
> +			if trustedSubnet != nil {
Старайся уменьшать вложенность кода. Здесь стоит проверять обратные условия

2024-10-10 22:03 UTC, sashaaro commented on internal/handlers/middleware.go
> +			if trustedSubnet != nil {
поправил

2024-10-10 22:03 UTC, sashaaro commented on internal/grpc/grpc_servcie.go
> +	key := s.genShortURLToken()
перенес genShortURLToken в домен

2024-10-15 08:33 UTC, s-shpak approved these changes

2024-10-21 16:31 UTC, merged