Iter5
sashaaro/url-shortener pull request #6
Opened 2024-03-12 15:59 UTC by sashaaro

2024-03-13 14:34 UTC, arttet requested changes
Please add
- https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- https://github.com/golangci/golangci-lint

2024-03-13 14:34 UTC, arttet commented on cmd/shortener/main.go
> +func initConfig() {
SUGGESTION: it would be better if it's in `flags.go`

2024-03-13 14:34 UTC, arttet commented on internal/infra/http.go
> +package infra
CLARIFICATION: please clarify and review your project layout.

2024-03-13 14:34 UTC, arttet commented on internal/infra/http.go
> +func GenShortURLToken() string {
CHANGE REQUEST: this is business logic here.

2024-03-13 14:34 UTC, arttet commented on internal/infra/http.go
> +	createShortHandler := func(writer http.ResponseWriter, request *http.Request) {
CHANGE REQUEST: it should be a method

2024-03-14 17:54 UTC, sashaaro commented on internal/infra/http.go
> +package infra
add handlers & adapters packages.

2024-03-14 18:01 UTC, sashaaro commented on internal/infra/http.go
> +func GenShortURLToken() string {
move to adapters

2024-03-14 18:02 UTC, sashaaro commented on internal/infra/http.go
> +	createShortHandler := func(writer http.ResponseWriter, request *http.Request) {
fixed

2024-03-14 18:06 UTC, sashaaro commented on cmd/shortener/main.go
> +func initConfig() {
created flags.go

2024-03-21 06:23 UTC, arttet approved these changes

2024-03-21 06:23 UTC, arttet commented on internal/adapters/repository.go
> +		urlStore: map[domain.HashKey]url.URL{},
```suggestion
		urlStore: make(map[domain.HashKey]url.URL),
```

2024-03-21 06:23 UTC, arttet commented on internal/handlers/handlers.go
> +	"io"
Please sort these imports
https://stackoverflow.com/questions/38704769/golang-import-grouping-by-package

2024-03-21 06:23 UTC, arttet commented on internal/handlers/handlers.go
> +type HTTPHandlers struct {
```suggestion
type Handler struct {
```

2024-03-26 17:48 UTC, merged